export class Artista {
  constructor(
    public userID: number,
    public name: string,
    public username: string,
    public userPicture: string,
    public backgroundPicture: string,
    public category: string,
    public subcategory: string,
    public description: string,
    public street: string,
    public number: number,
    public neighborhood: string,
    public zipCode: string,
    public city: string,
    public complement: string,
    public state: string,
    public userFacebook: string,
    public userInstagram: string,
    public userTwitter: string,
    public facebook: string,
    public instagram: string,
    public twitter: string,
    public mainPhone: string,
    public secundaryPhone: string,
    public thirdPhone: string,
    public facebookProfile: string,
    public twitterProfile: string,
    public whatsappProfile: string,
    public whatsappContact: string,
    public isPremium: boolean
  ) {}
}
