name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      
    - name: Install packages, build and test
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        installPackages: npm install
        installAngular: npm install -g @angular/cli
        buildCommand: ng build
        testCommnad: ng test
